http_exceptions/__init__.py,sha256=Wn3ODRHgdTuSoPRvfc-XSMb0BHgvf3t3txzCGCkn51A,2489
http_exceptions/client_exceptions.py,sha256=nFTWRJq6lto8V_tY8sKfcWK9r-Xvq54d2ESqo5MeyBk,9462
http_exceptions/http_exception.py,sha256=Q5IMWlpZUZD5ktNpKysWQzbHQtcyKtra_WNVtjsPKvQ,2231
http_exceptions/py.typed,sha256=dHaMYeog-n6iNI7LusnkAs74dFFA91AqOP7_KoQtpik,54
http_exceptions/server_exceptions.py,sha256=CsDRPZreIkZ70pBkvYsN7UDrCwWO2GmZkwIHHVzxm0Y,3849
http_exceptions-0.2.3.dist-info/METADATA,sha256=Y6f8XClYW4sCAoZpaJvWjePhjtCeOHdn4EHIVF_SKAw,6139
http_exceptions-0.2.3.dist-info/WHEEL,sha256=G16H4A3IeoQmnOrYV4ueZGKSjhipXx8zc8nu9FGlvMA,92
http_exceptions-0.2.3.dist-info/top_level.txt,sha256=nCsOu8w0eKykZ5L75RPpbMclcCQvAnVxrTtT26W_xiM,16
http_exceptions-0.2.3.dist-info/RECORD,,
